name: models-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.10
  
  # PyTorch with MPS support for Apple Silicon
  - pytorch>=2.1.0
  - torchvision>=0.16.0
  - torchaudio>=2.1.0
  
  # Core scientific computing
  - numpy>=1.24.0
  - pillow>=10.0.0
  - opencv>=4.8.0
  - scikit-image>=0.21.0
  - matplotlib>=3.7.0
  - pyyaml>=6.0
  - tqdm>=4.66.0
  - psutil>=5.9.0
  
  # Package management
  - pip
  
  # ML/AI packages (via pip for latest versions)
  - pip:
    - transformers>=4.36.0
    - diffusers>=0.25.0
    - accelerate>=0.25.0
    - huggingface-hub>=0.19.0
    - safetensors>=0.4.0
    - omegaconf>=2.3.0
    - einops>=0.7.0
    - imageio>=2.31.0
    - imageio-ffmpeg>=0.4.9
    - av>=10.0.0